#!/bin/bash
# Apply systemd-logind sleep/lid behavior for the current power source.
# Requires root (writes to /etc/systemd/logind.conf.d/).
#
# Behavior is read from the central config (POWER_CONFIG, or
# /etc/omarchy-power/power.conf by default); see config/power.conf for the
# available keys. The AC/battery profiles decide:
#
#   - what happens after idle (IdleAction / IdleActionSec)
#   - what happens when the lid closes (HandleLidSwitch variants)
#
# Screensaver and screen-off / lock timing are handled by the shell via
# ~/.config/omarchy/shell.json and are the same on both sources.

set -e

LOGIND_DIR="${LOGIND_DIR:-/etc/systemd/logind.conf.d}"
CONF="$LOGIND_DIR/20-user-power-behavior.conf"
CONFIG="${POWER_CONFIG:-/etc/omarchy-power/power.conf}"
SYSTEMCTL="${SYSTEMCTL:-systemctl}"

# Defaults matching the original hardcoded behavior, used when no config file
# is present or a key is missing.
AC_IDLE_ACTION="ignore"
AC_IDLE_ACTION_SEC="0"
AC_LID_SWITCH="ignore"
AC_LID_SWITCH_EXTERNAL_POWER="ignore"
AC_LID_SWITCH_DOCKED="ignore"
BATTERY_IDLE_ACTION="suspend"
BATTERY_IDLE_ACTION_SEC="1800"
BATTERY_LID_SWITCH="suspend"
BATTERY_LID_SWITCH_EXTERNAL_POWER="suspend"
BATTERY_LID_SWITCH_DOCKED="ignore"

# Load only plain KEY=VALUE lines from the config and validate them before
# assigning them to shell variables. This avoids eval-based execution while still
# supporting the repo's config format.
read_config() {
  local line key value

  [[ -r "$CONFIG" ]] || return 0

  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *=* ]] && continue

    key="${line%%=*}"
    value="${line#*=}"

    key="${key//[[:space:]]/}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    if [[ ! "$key" =~ ^[A-Z][A-Z0-9_]*$ ]]; then
      continue
    fi

    case "$key" in
      AC_IDLE_ACTION|AC_LID_SWITCH|AC_LID_SWITCH_EXTERNAL_POWER|AC_LID_SWITCH_DOCKED|BATTERY_IDLE_ACTION|BATTERY_LID_SWITCH|BATTERY_LID_SWITCH_EXTERNAL_POWER|BATTERY_LID_SWITCH_DOCKED)
        if [[ "$value" =~ ^[A-Za-z0-9_-]+$ ]]; then
          printf -v "$key" '%s' "$value"
        fi
        ;;
      AC_IDLE_ACTION_SEC|BATTERY_IDLE_ACTION_SEC)
        if [[ "$value" =~ ^[0-9]+$ ]]; then
          printf -v "$key" '%s' "$value"
        fi
        ;;
      *)
        ;;
    esac
  done < "$CONFIG"
}

read_config

power_source="${1:-}"
if [[ -z $power_source ]]; then
  if [[ $(busctl get-property org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower OnBattery 2>/dev/null) == *"true"* ]]; then
    power_source="battery"
  else
    power_source="ac"
  fi
fi

case "$power_source" in
  ac)
    IDLE_ACTION="${AC_IDLE_ACTION:-ignore}"
    IDLE_ACTION_SEC="${AC_IDLE_ACTION_SEC:-0}"
    LID_SWITCH="${AC_LID_SWITCH:-ignore}"
    LID_SWITCH_EXTERNAL_POWER="${AC_LID_SWITCH_EXTERNAL_POWER:-ignore}"
    LID_SWITCH_DOCKED="${AC_LID_SWITCH_DOCKED:-ignore}"
    ;;
  battery)
    IDLE_ACTION="${BATTERY_IDLE_ACTION:-suspend}"
    IDLE_ACTION_SEC="${BATTERY_IDLE_ACTION_SEC:-1800}"
    LID_SWITCH="${BATTERY_LID_SWITCH:-suspend}"
    LID_SWITCH_EXTERNAL_POWER="${BATTERY_LID_SWITCH_EXTERNAL_POWER:-suspend}"
    LID_SWITCH_DOCKED="${BATTERY_LID_SWITCH_DOCKED:-ignore}"
    ;;
  *)
    echo "Usage: $0 [ac|battery]" >&2
    exit 1
    ;;
esac

{
  cat <<EOF
# Generated by omarchy-power from $CONFIG
[Login]
HandleLidSwitch=$LID_SWITCH
HandleLidSwitchDocked=$LID_SWITCH_DOCKED
HandleLidSwitchExternalPower=$LID_SWITCH_EXTERNAL_POWER
IdleAction=$IDLE_ACTION
EOF
  if [[ $IDLE_ACTION != "ignore" && $IDLE_ACTION_SEC -gt 0 ]]; then
    echo "IdleActionSec=${IDLE_ACTION_SEC}s"
  fi
} > "$CONF"

# Reload, not restart: restarting logind tears down the session.
"$SYSTEMCTL" reload systemd-logind

echo "Power behavior set to: $power_source (idle=$IDLE_ACTION, lid=$LID_SWITCH)
  config=$CONFIG"
